/**
 * The Gekookt list itself: the union of its two card kinds, PD-020.1's
 * unseen band, and the `Vrienden · 2` count that reads the same rows
 * (docs/DESIGN.md §8, docs/DESIGN-SOCIAL.md §3.2 and §4.2).
 *
 * WHY A THIRD MODULE. friendFeedPresentation.ts owns the SEND card and
 * friendProofPresentation.ts owns the PROOF card, and neither imports the
 * other — PD-016's "a send may never borrow the language of proof" is
 * held in place by that separation. But the list holds both, and somebody
 * has to say in what order. Putting that in either card's module would
 * make one kind's file the authority over the other's placement, which is
 * the first crack in the separation. So the list is its own thing, it
 * imports both, and neither imports it.
 *
 * THE ONE RULE THIS FILE EXISTS TO ENFORCE: only directed sends have a
 * reader state. Ambient cook proof never does — not one card, ever,
 * however many friends cooked something today. §8: "a count fed by other
 * people's ordinary dinners is 'check back often' by another name; a count
 * of letters addressed to you is mail." PD-004 is the rule underneath:
 * this surface is measured on save-to-cook and never on dwell time.
 *
 * It is structural rather than conventional, and that is worth spelling
 * out because it is the reason this file is short. "Unseen" is a fact
 * about a `recipe_shares` row, so it is keyed on MEAL ids. A proof card
 * carries `recipeId` and declares `mealId?: never`, so it holds no key the
 * unseen set could match — a proof card cannot enter the band even if its
 * canonical recipe id happened to equal an unseen meal id, because there
 * is nothing to compare. `shared_cooks` likewise produces no `IncomingSend`
 * and therefore cannot reach the count. Neither guarantee depends on
 * anybody remembering §8.
 *
 * WHAT IS STILL NOT HERE, AND MUST NOT ARRIVE: a timestamp, a sort by
 * recency, a section header, a "NIEUW" divider, a per-card read stamp.
 * The band is a stable partition of an already-ranked list and nothing
 * more; the entrance motion is the only announcement it gets.
 *
 * No React Native import, so this is unit-testable directly under
 * vitest's `node` environment — the motion numbers below are plain
 * milliseconds and the components read the easing and duration tokens
 * themselves.
 */

import type { FriendRecipeCardModel } from './friendFeedPresentation';
import type { FriendProofCardModel } from './friendProofPresentation';
import type { IncomingSend } from '@/lib/repository/social/types';
import type { MealId } from '@/domain/types';

/**
 * One row of the Gekookt list: an ambient proof card, or a directed send
 * card.
 *
 * A UNION AND NOT A WRAPPER WITH A `kind` FIELD. The two models are
 * already mutually non-assignable by construction — a send has `mealId`
 * and no `recipeId`, a proof has `recipeId` and `mealId?: never` — so
 * `'recipeId' in card` narrows without anybody having to maintain a tag,
 * and a tag would be a second, hand-kept source of truth about which
 * renderer a card belongs to. Getting that tag wrong would hand a private
 * household row to the renderer that opens the world-readable one, or the
 * reverse; getting the union wrong does not compile.
 */
export type GekooktCard = FriendRecipeCardModel | FriendProofCardModel;

/**
 * Which renderer a card belongs to, decided by the identifier it actually
 * holds rather than by a label somebody attached.
 *
 * The narrowing is on `recipeId` and not on `mealId` deliberately.
 * `mealId?: never` makes `'mealId' in card` a question TypeScript
 * considers answerable in both directions on the proof side (the key is
 * declared, merely never present), while `recipeId` exists on exactly one
 * of the two shapes. One test, one direction, no ambiguity.
 */
export function isProofCard(card: GekooktCard): card is FriendProofCardModel {
  return 'recipeId' in card;
}

/**
 * A stable list key, namespaced by card kind.
 *
 * The prefix is not decoration. A send card is keyed by its feed item and
 * a proof card by its canonical recipe, and nothing guarantees those two
 * id spaces are disjoint — both are opaque strings, and 0006's `recipes`
 * ids and 0002's `feed_items` ids are generated by different tables. Two
 * rows sharing a key makes a list recycle the wrong component, which on
 * this screen means one card kind rendering with the other's data.
 */
export function getGekooktCardKey(card: GekooktCard): string {
  return isProofCard(card) ? `proof:${card.recipeId}` : `send:${card.feedItemId}`;
}

/**
 * How many unseen sends the tab label will name before it stops counting
 * exactly.
 *
 * DECIDED HERE, NOT INHERITED. §8 specifies the label as `Vrienden · 2`
 * and records no cap or overflow rule at all, so this constant is a
 * decision taken to ship the feature and it needs ratifying rather than
 * assuming. The argument for having one: the tab label is a mono
 * `typeScale.caption` sharing one row with three other words, so a
 * four-character count is a layout failure on a narrow phone — and the
 * count is unbounded in principle, since it only clears when somebody
 * opens the tab and a dormant account accumulates. The argument for 99
 * specifically: it is the largest count that fits the same width as the
 * realistic ones, and "99+" reads as a plain overflow rather than as an
 * alarm. Three digits is not realistic for directed sends between
 * mutually accepted friends, which is why this is a guard rather than a
 * feature.
 */
export const UNSEEN_TAB_COUNT_CEILING = 99;

/** The tab's own word, with nothing appended. Exported so the label and its spoken form cannot drift apart. */
export const VRIENDEN_TAB_TITLE = 'Vrienden';

/** The spoken label as it stood before PD-020.1, unchanged and still correct when nothing is waiting. */
export const VRIENDEN_TAB_ACCESSIBILITY_LABEL = 'Vrienden, recepten die vrienden met je deelden';

/** §8: staggered 40ms per card. */
export const UNSEEN_ENTRANCE_STAGGER_MS = 40;

/**
 * §8: capped at four. The cap is on the ACCUMULATION rather than on how
 * many cards animate — a fifth unseen card still fades in, it just does
 * not wait longer than the fourth. Capping the number of animated cards
 * instead would make the band's tail arrive unannounced while its head
 * was announced, which reads as a rendering bug.
 */
export const UNSEEN_ENTRANCE_STAGGER_LIMIT = 4;

/**
 * How many sends are waiting to be looked at — the number the tab label
 * carries.
 *
 * ITS ARGUMENT TYPE IS THE ENFORCEMENT. `IncomingSend` is the only shape
 * that carries `seen`, `listSendsToMe` is the only method that returns
 * it, and `shared_cooks` produces `FriendCook` rows which have no reader
 * state to have an unseen half of. So "ambient proof never feeds the
 * count" is not a filter anybody could forget to apply — there is no
 * value of any proof type that this function would accept.
 *
 * Withdrawn sends are already gone: `listSendsToMe` filters them at the
 * query in both backends, matching 0009's `where withdrawn_at is null`
 * index. This function therefore counts what §8 specifies exactly —
 * recipient is the reader, `withdrawn_at is null`, `seen_at is null` —
 * with the first two conditions applied by the repository and the third
 * here.
 */
export function countUnseenSends(sends: readonly IncomingSend[]): number {
  return sends.filter((send) => !send.seen).length;
}

/**
 * The meals whose send has not been looked at — the band's membership
 * test, as a set the list can ask cheaply per card.
 *
 * A SET OF MEAL IDS AND NOT OF SHARE IDS, because a card knows which meal
 * it shows and does not know which `recipe_shares` row brought it. That
 * is the same reason `SentMeal` carries `shareId` for the caller's own
 * pairing: the card model is deliberately ignorant of the send.
 */
export function collectUnseenSendMealIds(sends: readonly IncomingSend[]): ReadonlySet<MealId> {
  return new Set(sends.filter((send) => !send.seen).map((send) => send.mealId));
}

/**
 * The tab label: `Vrienden`, or `Vrienden · 2` while sends are waiting.
 *
 * A BURNED-IN FRAME COUNTER, NOT A BADGE. No dot, no `danger` red, no
 * colour of any kind, no animation — the count is part of the label
 * string and inherits the tab's own `typeScale.caption`, which is
 * monospace, so the number sits on the same rhythm as the word. A badge
 * would be a small red thing that appears and disappears in the corner of
 * the eye, which is the exact attention mechanic this product refuses.
 *
 * With nothing waiting the label is EXACTLY "Vrienden", byte for byte —
 * not "Vrienden · 0", not "Vrienden ·". A zero is still a number to
 * check.
 *
 * A non-positive or non-finite count falls back to the bare label rather
 * than rendering "Vrienden · NaN". Defensive, and cheap: the count
 * arrives from a live read that can be in flight.
 */
export function buildVriendenTabLabel(unseenCount: number): string {
  if (!Number.isFinite(unseenCount) || unseenCount <= 0) {
    return VRIENDEN_TAB_TITLE;
  }
  const shown =
    unseenCount > UNSEEN_TAB_COUNT_CEILING ? `${UNSEEN_TAB_COUNT_CEILING}+` : String(Math.floor(unseenCount));
  return `${VRIENDEN_TAB_TITLE} · ${shown}`;
}

/**
 * The spoken label, which states the count in words rather than leaving a
 * screen reader to voice a middot.
 *
 * "Vrienden · 2" is read aloud by VoiceOver as something between "Vrienden
 * punt 2" and "Vrienden 2", neither of which says what the number is. So
 * the spoken form spells the fact out — and spells it as a FACT: "2
 * recepten nog niet bekeken". Never "2 nieuwe recepten!", never "je hebt
 * 2 berichten". §8 is explicit that this must be a plain statement and
 * never an alarm, and a screen-reader user is exactly the person who
 * cannot glance at the tab and decide for themselves how urgent it looks.
 *
 * Dutch agreement is done properly rather than approximated, the same way
 * `buildFriendProofEyebrow` does it: one "recept", more than one
 * "recepten".
 *
 * Above the ceiling it says "meer dan 99" rather than reading "99+" out,
 * which a screen reader renders as "99 plus" — a sum, not a bound.
 */
export function buildVriendenTabAccessibilityLabel(unseenCount: number): string {
  if (!Number.isFinite(unseenCount) || unseenCount <= 0) {
    return VRIENDEN_TAB_ACCESSIBILITY_LABEL;
  }
  const count = Math.floor(unseenCount);
  const spokenCount = count > UNSEEN_TAB_COUNT_CEILING ? `meer dan ${UNSEEN_TAB_COUNT_CEILING}` : String(count);
  const noun = count === 1 ? 'recept' : 'recepten';
  return `${VRIENDEN_TAB_ACCESSIBILITY_LABEL}, ${spokenCount} ${noun} nog niet bekeken`;
}

/** The Gekookt list, ordered, plus where its band ends. */
export interface GekooktList {
  readonly cards: readonly GekooktCard[];
  /**
   * How many cards at the HEAD of `cards` are unseen sends. The band is a
   * prefix by construction, so one number describes it completely and the
   * list needs no per-card flag to animate the right rows.
   *
   * Zero is the ordinary state and renders as an ordinary list — there is
   * no header, no divider and no "NIEUW" label to hide, because there
   * never was one to show.
   */
  readonly unseenBandSize: number;
}

/**
 * PD-020.1's band: unseen sends grouped at the top, everything else
 * following in the order it arrived.
 *
 * A STABLE PARTITION, AND NOTHING ELSE. The caller hands this list
 * already ranked by `rankFeedItems` for cookability, and §8 says the band
 * is ordered "by `rankFeedItems` cookability WITHIN the group" — which is
 * precisely what preserving relative order gives, for free, in both
 * halves at once. Anything that re-sorted would be a second opinion about
 * cookability, and a comparator here is how a recency sort eventually
 * arrives: there is no timestamp on these models today, and the way one
 * gets used is that somebody adds a sort and then needs a key for it.
 *
 * NOT A SECTION LIST. It returns one flat array on purpose. A
 * `SectionList` would need section titles, and a section with a title is
 * one edit away from that title being "NIEUW" — the divider §8 refuses.
 * The entrance motion is the only announcement the band gets.
 *
 * A PROOF CARD CANNOT BE LIFTED. `unseenMealIds` holds meal ids and a
 * proof card has no meal id to match — see this file's header. The
 * membership test below asks `isProofCard` first anyway, so the intent is
 * legible without following the type argument, but the guarantee does not
 * rest on that line being there.
 *
 * Returns a new array; the input is never sorted in place.
 */
export function orderGekooktList(cards: readonly GekooktCard[], unseenMealIds: ReadonlySet<MealId>): GekooktList {
  const unseen: GekooktCard[] = [];
  const rest: GekooktCard[] = [];

  for (const card of cards) {
    if (!isProofCard(card) && unseenMealIds.has(card.mealId)) {
      unseen.push(card);
    } else {
      rest.push(card);
    }
  }

  return { cards: [...unseen, ...rest], unseenBandSize: unseen.length };
}

/**
 * How long a card waits before its entrance runs, or null for "already at
 * rest".
 *
 * NULL IS NOT ZERO, and the difference matters. Zero means "animate, now";
 * null means there is no entrance at all and the card renders at its final
 * opacity and offset. Every card below the band gets null, because the
 * band's entrance IS the announcement and animating the rest of the list
 * would say "everything here is new" — which is the freshness claim this
 * whole surface refuses.
 *
 * REDUCED MOTION RETURNS NULL FOR EVERYTHING: "everything lands instantly,
 * no stagger". Not a shortened duration and not a zero delay — the card
 * simply starts where it ends. Note the contrast with PD-020.2's
 * closed-loop haptic, which SURVIVES reduced motion because a haptic is
 * feedback rather than motion; a fade is motion, so it goes.
 *
 * The cap is on the accumulated delay, not on how many cards animate —
 * see `UNSEEN_ENTRANCE_STAGGER_LIMIT`.
 */
export function resolveUnseenEntranceDelay(
  index: number,
  unseenBandSize: number,
  reduceMotionEnabled: boolean,
): number | null {
  if (reduceMotionEnabled || index < 0 || index >= unseenBandSize) {
    return null;
  }
  return Math.min(index, UNSEEN_ENTRANCE_STAGGER_LIMIT - 1) * UNSEEN_ENTRANCE_STAGGER_MS;
}
